### ISSUE TITLE
Feature request: Changing logger

### ISSUE THREAD

**Issue by Mik13** [strangerlabs/webauthn#10]
Currently, everything is logged to console, which might pollute things like syslog etc.

There should be a possibility, to change the logger, like this: https://github.com/Mik13/webauthn/commit/929ed75aa2140f2c41f3eed9251223ccb654310c

**Comment by inorganik** [comment]
Would love an option in the initializer to disable logging.

**Comment by Mik13** [comment]
Using console as a logger is quite bad. Are you sure you do not want a customizeable logging feature like the one I proposed? I could create a merge request, but did not do so yet because of the pull request policy you put in your readme.

**Comment by EternalDeiwos** [comment]
@Mik13 I wouldn't mind merging something like that if you wanted to create a PR for it for now. The log statements themselves were just for debugging / demonstration purposes so the main idea of @inorganik's PR was to disable them -- not necessarily to have a "real logger".

We're currently working on something else so we're not able to give this our full attention to develop it further yet (specifically to accomodate the full range of preferences of the WebAuthn spec.). We hope to not change the interface and behaviour described in `README.md` too much, but everything behind it is subject to change.
