### ISSUE TITLE
Feature request: Changing attestation type

### ISSUE THREAD

**Issue by Mik13** [strangerlabs/webauthn#11]
Attestation type should be changeable, because "direct" (the only possibility currently) is not always wanted and/or needed.

Maybe we can allow indirect and none too (for this, the none format must be implemented too).

Example here: https://github.com/Mik13/webauthn/commit/08964499f09c7c6c99ed3558badfb8b07a504c4c

**Comment by EternalDeiwos** [comment]
I would say that this is fixed but currently when I try it I still tend to get a 'direct' attestation even if I explicitly ask for 'none'. Closing this and opened separate issue for the bug at #30.
