### ISSUE TITLE
Support and default to none attestation

### ISSUE THREAD

**Issue by nsatragno** [strangerlabs/webauthn#18]
The library should support and default to [`none` attestation](https://w3c.github.io/webauthn/#sctn-none-attestation), as requiring it has some privacy implications and includes dissuading language on browsers. Also, validating the attestation means the backend has to talk to the FIDO MDS which adds complexity that a developer might not need in their application.

**Comment by EternalDeiwos** [comment]
Hey, just finished going over the PR (#19) and it looks good to me. One thing I would mention is that we have plans to refactor out the attestation formats and the COSE algorithms into separate files; we'll write up more details on that shortly.

Thanks for the issue and the PR 😄
