### ISSUE TITLE
Support for Node 6.x.x

### ISSUE THREAD

**Issue by Ylianst** [strangerlabs/webauthn#2]
Thanks for working on WebAuthn, super important.

I am building MeshCentral (https://www.npmjs.com/package/meshcentral) and really need to support YubiKey, FIDO and FIDO2 (WehAuthn). I support it now using some dependency libraries I don't like and would like to start using a more supported library. One of the requirements I have is to make MeshCentral work on Node 6.0.0 and higher. So far it's not been an issue at all, however the "await" and "async" syntax in this library breaks older node versions. Is there a work around for this?

Also, I am using "forge" as my crypto and would like to use that as the crypto provider. i wonder if there could be an option for this. Right now, it looks like I am going to have to build something custom. Any opinions would be great.

**Comment by EternalDeiwos** [comment]
Hey @Ylianst,

We don't plan on supporting Node 6.x due to it becoming unmaintained as of the beginning of this month -- as `async` and `await` are fully supported in Node 8.x and above we didn't see any reason not to use those features or provide a workaround otherwise.

We plan on gradually expanding the list of supported algorithms using Node's built-in crypto module as it is FIPS certified and backed by OpenSSL. We'll eventually support at least those algorithms recommended by [RFC8152](https://tools.ietf.org/html/rfc8152). We do not plan to make the crypto system externally extensible as this could introduce major vulnerabilities.

**Comment by christiansmith** [comment]
Hi @Ylianst, thanks for the issue :) Aside from the async syntax and more algorithms, is there anything else you're looking for in a webauthn package?

**Comment by Ylianst** [comment]
Thanks. I fully understand not supporting older versions of NodeJS. I currently use U2F on Node 6.x and 7.x and WebAuthn for Node 8.x and higher. I guess I will continue to do this. My number one ask is for product quality code. It's weird to increase security of MeshCentral with WebAuthn and be told at the same time that it's not product quality code and so, it's bad for security.

I have a strict requirement that I can't use any modules that use native code. Also minimizing the number of dependencies is a really good thing, it speeds up installation of MeshCentral and lowers the number of modules to scan.

**Comment by Ylianst** [comment]
Thanks. I fully understand not supporting older versions of NodeJS. I currently use U2F on Node 6.x and 7.x and WebAuthn for Node 8.x and higher. I guess I will continue to do this. My number one ask is for product quality code. It's weird to increase security of MeshCentral with WebAuthn and be told at the same time that it's not product quality code and so, it's bad for security.

I have a strict requirement that I can't use any modules that use native code. Also minimizing the number of dependencies is a really good thing, it speeds up installation of MeshCentral and lowers the number of modules to scan.

**Comment by EternalDeiwos** [comment]
We're definitely committed to publishing good quality code. Our currently published version is there to demonstrate the basic functionality of the library. We're looking for early feedback from users to help us prioritise features we develop. We just started work on this 22 days ago (as of 16.05.19) and we still plan on writing tests and publishing proper documentation before we'll consider recommending this for production. As for native code, we don't plan to use any native dependencies aside from the NodeJS `crypto` module.
