### ISSUE TITLE
Support for attestation: 'none'

### ISSUE THREAD

**Issue by Ylianst** [strangerlabs/webauthn#3]
Any way you could add support for attestation: 'none' when doing the registration challenge? I want to be able to use U2F without having the browser prompt the user for extended information.

Thanks.

**Comment by Ylianst** [comment]
Closing this since I figured out how to make it work myself.

**Comment by strugee** [comment]
@Ylianst can you share how you did so? It's pretty frustrating to stumble across this issue having the exact same problem myself.

Also, can you reopen? Even if there's a workaround, the library should still properly/officially support this functionality.

**Comment by Ylianst** [comment]
Sure. I am one of the authors of [MeshCentral](https://github.com/Ylianst/MeshCentral) and have been looking for a simple FIDO2/WebAuthn module for a while and could not find any I liked. I also wanted it to work on Node 6.x. Eventually, I built my own. Look for "webauthn.js" in the [MeshCentral github](https://github.com/Ylianst/MeshCentral). It's a stripped down version of this one. I am not going to re-open since I don't use this library anymore. Hope it helps.
