### ISSUE TITLE
Valid key assertion not working

### ISSUE THREAD

**Issue by brianmhunt** [strangerlabs/webauthn#4]
FYI I gave this a whirl and it works great with most keys (U2F, FIDO, MacBook fingerprint), but here's a device where it fails to work:

  - MacBook Pro (Model A1989) 
  - OS X 10.14.5
  - Chrome 74.0.3729.169 (64 bit)
  - Fingerprint sensor

```js
const webauthn = require('./Webauthn')

y = {
    "publicKey": "BE6dYDmxeWIXbCM6DYqU3Yxg1PynoYl0rLei25QXksxicNIXH0iGtDW05IrbiwrXIzE9NI5-UdsP_pdFKkcHG-E",
    fmt: "fido-u2f"
}
x = {
    "authenticatorData": "SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NFXPgtka3OAAI1vMYKZIsLJfHwVQMAgADpMeDIZQ9uUOKrShQMWdsX9Px2Uo3ZVoCZFpBkr_CQ9tsHHfdu7foaUKxY1UMZiERyeGUo4yq37METlvOwPjZtVXr4NdhoDF4nxiGr2eaHfg-XC3fqkKZUN36H63xxcEDlczfpx-vcbdw_ZtPRHKgQZiqw2gRSmBpTxCPVtX-3pQECAyYgASFYIE6dYDmxeWIXbCM6DYqU3Yxg1PynoYl0rLei25QXksxiIlggcNIXH0iGtDW05IrbiwrXIzE9NI5-UdsP_pdFKkcHG-E",
    "signature": "MEUCIQCtiRBFexiFuwXDL_JirFkG_xyFsPgS7GzjYJ3Mr3j86QIgT3fYOtqCmMtKxCpo7pDlEIfaxiyPyqcqVYQVwpFQw84",
    "userHandle": "ODY1MTg2NDItZjgzMC00ODI5LWI2MDYtYjFiMzA1ZDRmYWRk",
    "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJZaGZNc2hDMWJNTV9aeTVCSzBRZ3VGNWZpRXY1bk9EVE5IaVpTSVJzak04Iiwib3JpZ2luIjoiaHR0cDovL2xvY2FsaG9zdDo3MTAwIiwidHlwZSI6IndlYmF1dGhuLmdldCJ9"
}
t = webauthn.verifyAuthenticatorAssertionResponse(x, y)
console.log('y', t.verified)
```

With the device, attestation works, but assertion fails.

I'll be looking into it more and will report in if I figure out the solution.

Thanks for the great work here.  Cheers.

**Comment by brianmhunt** [comment]
It looks like `src/Webauthn.js`:

```js
514      const signatureBase = Buffer.concat([authrDataStruct.rpIdHash, authrDataStruct.flagsBuf, authrDataStruct.counterBuf, clientDataHash])
```

should be

```js
      const signatureBase = Buffer.concat([authenticatorData, clientDataHash])
```

https://www.w3.org/TR/webauthn/#verifying-assertion section 16:

> Using the credential public key looked up in step 3, verify that sig is a valid signature over the binary concatenation of authData and hash.

**Comment by StefanGussner** [comment]
Why is this issue closed?
I had the same problem and the same solution worked.

**Comment by brianmhunt** [comment]
@StefanGussner I must've hit "close" by accident.

**Comment by StefanGussner** [comment]
When is this fix gonna be published?

**Comment by EternalDeiwos** [comment]
@StefanGussner I'm currently swamped and haven't had a chance to make progress on plans for this library. That being said I could probably find a few minutes to look at this next week. Alternatively I would also be happy to accept a pull request for this if you need it sooner.

**Comment by StefanGussner** [comment]
I have tested the fix and created a PR.

**Comment by EternalDeiwos** [comment]
Thanks for the PR @StefanGussner. Publishing now.
